In [5]:
import numpy as np
import pandas as pd
#======TA==============
from ta.momentum import *
from ta.trend import *
from ta.volatility import *
from ta.wrapper import *
import ta
#======================

In [ ]:
df = pd.DataFrame(np.arange(0, 100, 1, dtype=int))

In [60]:
df = pd.DataFrame(np.arange(0, 100, 1, dtype=int))

In [ ]:
df = pd.DataFrame(np.random.randint(-100,100,(50,1)))

In [61]:
df['diff_close'] = df[0] - df[0].shift(1)
df.head()

   0  diff_close
0  0         NaN
1  1         1.0
2  2         1.0
3  3         1.0
4  4         1.0

In [62]:
window_slow = 25
window_fast = 13
min_periods_r = 0
min_periods_s = 0

In [63]:
df['smoothed'] = df['diff_close'].ewm(
                span=window_slow, min_periods=min_periods_r, adjust=False
            ).mean().ewm(span=window_fast, min_periods=min_periods_s, adjust=False).mean()

In [64]:
dir(df['diff_close'].ewm(
                span=window_slow, min_periods=min_periods_r, adjust=False
            ))

['__annotations__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_apply_blockwise',
 '_apply_pairwise',
 '_apply_series',
 '_apply_tablewise',
 '_attributes',
 '_check_window_bounds',
 '_com',
 '_create_data',
 '_deltas',
 '_dir_additions',
 '_get_window_indexer',
 '_gotitem',
 '_index_array',
 '_insert_on_column',
 '_internal_names',
 '_internal_names_set',
 '_is_protocol',
 '_numba_apply',
 '_obj_with_exclusions',
 '_on',
 '_prep_values',
 '_resolve_output',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_validate',
 '_win_freq_i8',
 '_win_type',
 'adjust',
 'agg',
 'aggregate',
 'alpha',
 'axis',
 'center',
 'closed',
 'com',
 'corr',
 'cov',
 'exclusions',
 'halflife',
 'ignore_na',
 'is_datetimelike',
 'mean',
 'method',
 'min_periods',
 'ndim',
 'obj',
 'on',
 'online',
 'span',
 'std',
 'sum',
 'times',
 'validate',
 'var',
 'vol',
 'win_type',
 'window']

In [65]:
a = df['diff_close'].ewm(
                span=window_slow, min_periods=min_periods_r, adjust=False
            )

In [66]:
a.method

'single'

In [67]:
#1
a.mean()

0     NaN
1     1.0
2     1.0
3     1.0
4     1.0
     ...
95    1.0
96    1.0
97    1.0
98    1.0
99    1.0
Name: diff_close, Length: 100, dtype: float64

In [68]:
#2
a.mean().ewm(span=window_fast, min_periods=min_periods_s, adjust=False).mean()

0     NaN
1     1.0
2     1.0
3     1.0
4     1.0
     ...
95    1.0
96    1.0
97    1.0
98    1.0
99    1.0
Name: diff_close, Length: 100, dtype: float64

In [17]:
# TSI Indicator
df["momentum_tsi"] = TSIIndicator(
    close=df[0], window_slow=25, window_fast=13, fillna=True
).tsi()/100 #scale 0-1

In [18]:
df[20:80]

     0  momentum_tsi
20  30           1.0
21  31           1.0
22  32           1.0
23  33           1.0
24  34           1.0
25  35           1.0
26  36           1.0
27  37           1.0
28  38           1.0
29  39           1.0
30  40           1.0
31  41           1.0
32  42           1.0
33  43           1.0
34  44           1.0
35  45           1.0
36  46           1.0
37  47           1.0
38  48           1.0
39  49           1.0
40  50           1.0
41  51           1.0
42  52           1.0
43  53           1.0
44  54           1.0
45  55           1.0
46  56           1.0
47  57           1.0
48  58           1.0
49  59           1.0
50  60           1.0
51  61           1.0
52  62           1.0
53  63           1.0
54  64           1.0
55  65           1.0
56  66           1.0
57  67           1.0
58  68           1.0
59  69           1.0
60  70           1.0
61  71           1.0
62  72           1.0
63  73           1.0
64  74           1.0
65  75           1.0
66  76           1.0
67  77           1.0
68  78           1.0
69  79           1.0
70  80           1.0
71  81           1.0
72  82           1.0
73  83           1.0
74  84           1.0
75  85           1.0
76  86           1.0
77  87           1.0
78  88           1.0
79  89           1.0

manually for tsi

In [7]:
df['diff_close'] = df[0]-df[0].shift(1)
df

     0  momentum_tsi  diff_close
0  100      0.000000         NaN
1  120      1.000000        20.0
2  100      0.978022       -20.0
3   90      0.949608       -10.0
4   95      0.926856         5.0
5  110      0.909011        15.0
6  120      0.895010        10.0

In [13]:
df['diff_close'].ewm(span=25, min_periods=0, adjust=False).mean()

0          NaN
1    20.000000
2    16.923077
3    14.852071
4    14.094219
5    14.163895
6    13.843595
Name: diff_close, dtype: float64

In [ ]:
# window = 30 # a choice
# df[f"roc_{window}"] = ta.momentum.ROCIndicator(close=df["Close"], window=window).roc()
# df[f"roc_{window}"] = ta.momentum.ROCIndicator(close=df["Close"], window=window).roc()

# # Relative Strength Index (RSI)
# df["momentum_rsi"] = RSIIndicator(
#     close=df["Close"], window=14, fillna=True
# ).rsi()/100 #scale 0-1

# # Stoch RSI (StochRSI)
# indicator_srsi = StochRSIIndicator(
#     close=df["Close"], window=14, smooth1=3, smooth2=3, fillna=True
# )
# df["momentum_stoch_rsi"] = indicator_srsi.stochrsi()
# df["momentum_stoch_rsi_k"] = indicator_srsi.stochrsi_k()
# df["momentum_stoch_rsi_d"] = indicator_srsi.stochrsi_d()

# # TSI Indicator
# df["momentum_tsi"] = TSIIndicator(
#     close=df["Close"], window_slow=25, window_fast=13, fillna=True
# ).tsi()/100 #scale 0-1